--@Autor(es):       Jorge Rodríguez
--@Fecha creación:  dd/mm/yyyy
--@Descripción:     Creación de objetos

Prompt conectando como vald_p0801_viajes
connect vald_p0801_viajes

Prompt creando objetos

-- 
-- SEQUENCE: HISTORICO_ESTATUS_VIAJE_SEQ 
--

CREATE SEQUENCE HISTORICO_ESTATUS_VIAJE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: VIAJE_DETALLE_SEQ 
--

CREATE SEQUENCE VIAJE_DETALLE_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: ESTATUS_VIAJE 
--

CREATE TABLE ESTATUS_VIAJE(
    ESTATUS_VIAJE_ID    NUMBER(2, 0)    NOT NULL,
    CLAVE               VARCHAR2(20)    NOT NULL,
    ACTIVO              NUMBER(1, 0)    NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (ESTATUS_VIAJE_ID)
)
;



-- 
-- TABLE: LUGAR 
--

CREATE TABLE LUGAR(
    LUGAR_ID       NUMBER(10, 0)    NOT NULL,
    NOMBRE         VARCHAR2(100)    NOT NULL,
    DESCRIPCION    VARCHAR2(500),
    CONSTRAINT PK5 PRIMARY KEY (LUGAR_ID)
)
;



-- 
-- TABLE: MEDIO_TRANSPORTE 
--

CREATE TABLE MEDIO_TRANSPORTE(
    MEDIO_TRANSPORTE_ID      NUMBER(10, 0)    NOT NULL,
    TIPO_MEDIO_TRANSPORTE    CHAR(1)          NOT NULL,
    CAPACIDAD                NUMBER(3, 0)     NOT NULL,
    CLASE                    CHAR(1)          NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (MEDIO_TRANSPORTE_ID)
)
;



-- 
-- TABLE: VIAJE 
--

CREATE TABLE VIAJE(
    VIAJE_ID               NUMBER(10, 0)    NOT NULL,
    FECHA_SALIDA           DATE             NOT NULL,
    FECHA_ESTATUS           DATE             NOT NULL,
    ORIGEN_ID              NUMBER(10, 0)    NOT NULL,
    DESTINO_ID             NUMBER(10, 0)    NOT NULL,
    MEDIO_TRANSPORTE_ID    NUMBER(10, 0),
    ESTATUS_VIAJE_ID       NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (VIAJE_ID), 
    CONSTRAINT RefLUGAR33 FOREIGN KEY (ORIGEN_ID)
    REFERENCES LUGAR(LUGAR_ID),
    CONSTRAINT RefLUGAR43 FOREIGN KEY (DESTINO_ID)
    REFERENCES LUGAR(LUGAR_ID),
    CONSTRAINT RefMEDIO_TRANSPORTE53 FOREIGN KEY (MEDIO_TRANSPORTE_ID)
    REFERENCES MEDIO_TRANSPORTE(MEDIO_TRANSPORTE_ID),
    CONSTRAINT RefESTATUS_VIAJE83 FOREIGN KEY (ESTATUS_VIAJE_ID)
    REFERENCES ESTATUS_VIAJE(ESTATUS_VIAJE_ID)
)
;



-- 
-- TABLE: HISTORICO_ESTATUS_VIAJE 
--

CREATE TABLE HISTORICO_ESTATUS_VIAJE(
    HISTORICO_ESTATUS_VIAJE_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_ESTATUS                 DATE             NOT NULL,
    VIAJE_ID                     NUMBER(10, 0)    NOT NULL,
    ESTATUS_VIAJE_ID             NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (HISTORICO_ESTATUS_VIAJE_ID), 
    CONSTRAINT RefVIAJE93 FOREIGN KEY (VIAJE_ID)
    REFERENCES VIAJE(VIAJE_ID),
    CONSTRAINT RefESTATUS_VIAJE103 FOREIGN KEY (ESTATUS_VIAJE_ID)
    REFERENCES ESTATUS_VIAJE(ESTATUS_VIAJE_ID)
)
;



-- 
-- TABLE: MEDIO_AEREO 
--

CREATE TABLE MEDIO_AEREO(
    MEDIO_TRANSPORTE_ID    NUMBER(10, 0)    NOT NULL,
    AEROLINEA              VARCHAR2(50)     NOT NULL,
    NUMERO_AVION           VARCHAR2(6)      NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY (MEDIO_TRANSPORTE_ID), 
    CONSTRAINT RefMEDIO_TRANSPORTE13 FOREIGN KEY (MEDIO_TRANSPORTE_ID)
    REFERENCES MEDIO_TRANSPORTE(MEDIO_TRANSPORTE_ID)
)
;



-- 
-- TABLE: MEDIO_TERRESTRE 
--

CREATE TABLE MEDIO_TERRESTRE(
    MEDIO_TRANSPORTE_ID    NUMBER(10, 0)    NOT NULL,
    MATRICULA              NUMBER(5, 0),
    LINEA_TERRESTRE        VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (MEDIO_TRANSPORTE_ID), 
    CONSTRAINT RefMEDIO_TRANSPORTE23 FOREIGN KEY (MEDIO_TRANSPORTE_ID)
    REFERENCES MEDIO_TRANSPORTE(MEDIO_TRANSPORTE_ID)
)
;



-- 
-- TABLE: PASAJERO 
--

CREATE TABLE PASAJERO(
    PASAJERO_ID           NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(50)     NOT NULL,
    APELLIDO_PATERNO      VARCHAR2(50)     NOT NULL,
    APELLIDO_MATERNO      VARCHAR2(50),
    EDAD                  NUMBER(3, 0),
    TELEFONO              VARCHAR2(20),
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (PASAJERO_ID)
)
;



-- 
-- TABLE: VIAJE_DETALLE 
--

CREATE TABLE VIAJE_DETALLE(
    VIAJE_DETALLE_ID    NUMBER(18, 0)    NOT NULL,
    NUMERO_ASIENTO      VARCHAR2(3)      NOT NULL,
    VIAJE_ID            NUMBER(10, 0)    NOT NULL,
    PASAJERO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (VIAJE_DETALLE_ID), 
    CONSTRAINT RefVIAJE63 FOREIGN KEY (VIAJE_ID)
    REFERENCES VIAJE(VIAJE_ID),
    CONSTRAINT RefPASAJERO73 FOREIGN KEY (PASAJERO_ID)
    REFERENCES PASAJERO(PASAJERO_ID)
)
;


Prompt Listo!
disconnect